= SpecMan
Raphael Kuster <raphael.f.kuster@gmail.com>
v1.0, 2019-10-11
:toc:
:imagesdir: assets/images
:homepage: https://bighoss.github.io

Specification Manager - Tool to manage Software Specification Sheets and Documentation

== Problem
Software Specifications and Documentations are mostly done in word documents, sent to and forth to the customer and possibly even internally at a company.

The concrete problems with this way are the following:
- multiple versions at different locations
- copy of the standard spec for customer (when fixes or advncements are done in the customer version they are possibly not mirrored over to the standard document)
- possibly multiple designs for different parts of the same software
- new features are possibly not documented or in the specs at all

== Concept for a Solution
Manage the specifications in a dynamic fashion by using textblocks in a tree structure.

=== Needed Types of Nodes
* <<_Textblock>>[Textblocks]
* <<_Header>>[Headers]

=== Textblock
When you add in a textblock you have to specify a header for it, when entering the heading all already available textblocks will be searched.

=== Header
The level of the heading is depending on the hierarchy of the document.
Heading is just a textblock without text

== Technical ideas
* [ ] Text content is written in markdown
* [ ] IDE Integration
* [ ] Link Texblocks to Solutions
